name: 'merge-forward'
on:
  push:
    branches:
      - main

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: NicholasBoll/action-forward-merge-pr@0.0.1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          branches: main+prerelease/v5
